### ISSUE TITLE
Crash when enabling passcode

### ISSUE THREAD

**Issue by ysong10** [ysong10/fast_ALS#200]
Crash when enabling passcode.  The passcode screen should appear so I can enter the passcode.

**Comment by ojcchar** [comment]
Crash when enabling passcode.  The passcode screen should appear so I can enter the passcode. ![#FF0000](https://placehold.it/12/ff0000?text=+) [OB]
```diff
- The system’s expected behavior and steps to reproduce are missing!
```

**Comment by ojcchar** [comment]
**Legend:**
![#FF0000](https://placehold.it/12/ff0000?text=+) Observed behavior (OB)
![#FF0000](https://placehold.it/12/9900c5?text=+) Expected behavior (EB)
![#FF0000](https://placehold.it/12/157500?text=+) Steps to Reproduce (S2R)

**Title:** Crash when enabling passcode.![#FF0000](https://placehold.it/12/ff0000?text=+)

**Description:** 
Crash when enabling passcode.![#FF0000](https://placehold.it/12/ff0000?text=+) The passcode screen should appear so I can enter the passcode.![#FF0000](https://placehold.it/12/9900c5?text=+)

**Comment by ojcchar** [comment]
**Quality assessment:**
```diff
-The system’s expected behavior and steps to reproduce are missing!
```

@ysong10 can you provide this information in the bug report?

**Comment by ojcchar** [comment]
**Legend:**
![#FF0000](https://placehold.it/12/ff0000?text=+) Observed behavior (OB)
![#FF0000](https://placehold.it/12/9900c5?text=+) Expected behavior (EB)
![#FF0000](https://placehold.it/12/157500?text=+) Steps to Reproduce (S2R)

**Title:** Crash when enabling passcode.![#FF0000](https://placehold.it/12/ff0000?text=+)

**Description:** 
Crash when enabling passcode.![#FF0000](https://placehold.it/12/ff0000?text=+) The passcode screen should appear so I can enter the passcode.![#FF0000](https://placehold.it/12/9900c5?text=+)

**Comment by ojcchar** [comment]
**Quality assessment:**
```diff
-The system’s expected behavior and steps to reproduce are missing!
```

@ysong10 can you provide this information in the bug report?


**Legend:**
![#FF0000](https://placehold.it/12/ff0000?text=+) Observed behavior (OB)
![#FF0000](https://placehold.it/12/9900c5?text=+) Expected behavior (EB)
![#FF0000](https://placehold.it/12/157500?text=+) Steps to Reproduce (S2R)

**Title:** Crash when enabling passcode.![#FF0000](https://placehold.it/12/ff0000?text=+)

**Description:** 
Crash when enabling passcode.![#FF0000](https://placehold.it/12/ff0000?text=+) The passcode screen should appear so I can enter the passcode.![#FF0000](https://placehold.it/12/9900c5?text=+)
